version: "3"

services:
  swampadvert:
    image: nginx:stable-alpine
    container_name: swampadvert
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./play.shinysocks.net.conf:/etc/nginx/conf.d/play.shinysocks.net.conf
      - ./src:/usr/share/nginx/html
